### ISSUE TITLE
How did you print the multi page screenshot of quiz in each chapters.

### ISSUE THREAD

**Issue by anandkulkarnisg** [launchcode01dl/mathematics-for-machine-learning-cousera#2]
I would like to know how you printed the quiz questions which span multi page ? i am using firefox on Linux and trying my best to print quiz papers without success. Even i have tried third party tools but they cant handle page break etc properly. 

Keen to know how you did it ?

**Comment by launchcode01dl** [comment]
If you were on Windows 10, I would have suggested ShareX or PickPick. Both support scrolling windows screenshot, thougth I find PickPick to be better at it.
For Linux, I can't give a recommendation as I use it rarely. I do have an advice for you as you use firefox and if I remember correctly I also used this feature for those screenshots.
There is an option in firefox when taking screenshot, just right click on an empty part of a webpage and select "Take Screenshot" and you will see the option to capture whole page on top right. Hope this helps.
I have attached an image which shows this:
![image](https://user-images.githubusercontent.com/43728302/87914333-03582180-ca60-11ea-9a75-a52dc3730c40.png)
![image](https://user-images.githubusercontent.com/43728302/87914371-110da700-ca60-11ea-827f-599373fa4a8c.png)

**Comment by launchcode01dl** [comment]
Weird. I just tried again to use firefox screenshot and PickPick to capture the whole quiz of a course on coursera and it didnt work!
I think this is because Coursera changed the frontend code so that this quiz page has its own custom scollbar and therefore autoscroll would not work when taking the scrolling screenshot.
I guess we have no option now and will have to take multiple screenshots.

**Comment by anandkulkarnisg** [comment]
I have been able to fix multi page printing with chrome browser using a plug-in called GoFullPage
